// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package store

import (
	"database/sql"
	"time"

	pgvector_go "github.com/pgvector/pgvector-go"
)

type Entry struct {
	ID        int32
	Text      sql.NullString
	CreatorID string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Embedding pgvector_go.Vector
}
